### ISSUE TITLE
Compile error [voicount, serialize]

### ISSUE THREAD

**Issue by jcerveto** [humdrum-tools/humdrum-tools#10]
Hi! I'm looking for compiling this project but I encountered a compilation error when executing ```make```. My goal is to use 
[voicecount](https://extras.humdrum.org/man/voicecount/)  and [serialize](https://extras.humdrum.org/man/serialize/). I am able to run some other functions, but none of those mentioned. Perhaps I am performing a compilation step incorrectly. I would appreciate some help. Thank you.

Actually, if anyone could upload a binary file for voicecount and serialize, it would be amazing. There are a lot of binary files in [extras.humdrum.org/man/serialize/](https://extras.humdrum.org/bin/osxintel64/) but that functions are not there.
<br>

I download the complete project, I download the last commit (4543f1260bcb2f8459ad7908e69b3d15072449bc) of January 14.
```bash
   git clone --recursive https://github.com/humdrum-tools/humdrum-tools
```

Then I set the PATH using bash:
```bash
    PATH=`pwd`/humdrum/bin:$PATH
    PATH=`pwd`/humextra/bin:$PATH
```

The last compiling log printed is:
```bash
/bin/sh: 1: [[: not found
[CC] bin/humplay
cli/humplay.cpp:24:10: fatal error: synthImprov.h: No such file or directory
   24 | #include "synthImprov.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile.programs:379: bin/humplay] Error
```

I checked the make regression command, and it seems to be fine. The last tests passed are:
```bash
rm2kern	test 011 OK	Adding duration information to the **kern output.
harm2kern	test 012 OK	Preventing duration information from being added to the **kern output.
harm2kern	test 013 OK	Secondary dominants.
hgrep		test 001 OK	Search for "16g" only in data records, printing measure/beat where a match is found.
hum2abc		test 001 OK	Converting a melody into ABC plus.
hum2gmn		test 001 OK	D major scale with mixed rhythms.
hum2gmn		test 002 OK	Adding barline numbers.
hum2muse	test 001 OK	Measure the beat position of each point in the score.
hum2xml		test 001 OK	Translate a simple example into MusicXML data.
make[2]: 'leaves the directory' '/my-path/humdrum-tools/humextra/example'
```

Right now, I only can use this functions:
```
ls humextra/bin/
```
```
activity   barnum  cint        event          gettime    hum2abc  hum2mid   hummath     motion     sortcount
autodynam  beat    dittox      extractx       gptab2str  hum2enp  hum2muse  humpdf      partjoin   webnote
autostem   blank   dotproduct  finalis        harm2kern  hum2gmn  hum2xml   introspect  README.md  webscore
barline    chorck  esac2hum    finalis-tonic  hgrep      hum2mei  humcat    lyrics      sdmarkov
```

Furthermore, I would like to express my gratitude for this useful library.

**Comment by craigsapp** [comment]
The problem is the `humplay` program which has problems compiling.   This will happen on certain platforms where there was a problem compiling the improv library to deal with MIDI output (humplay plays Humdrum files in realtime via MIDI).   This happens in WSL (Windows Subsystem for Linux), and probably in linux if the ALSA development libraries are not installed.  (It should not have a problem in MacOS).

The best thing to do is to delete or move `humdrum-tools/humextra/cli/humplay.cpp`.  Then go to the `humdrum-tools` directory and run the `make` command again.

**Comment by jcerveto** [comment]
Hi! It worked when I moved ```humdrum-tools/humextra/cli/humplay.cpp``` out. I am using Ubuntu 22.04 as my operating system. Thank you very much. 💪
