### ISSUE TITLE
Perform: command not found

### ISSUE THREAD

**Issue by lumingpuchheim** [humdrum-tools/humdrum-tools#3]
Latest commit date: 2019-11-17
Compilation is ok, path has been added correctly

**Comment by craigsapp** [comment]
Perform no longer exists (it was created for MS-DOS).   The humplay tool serves as a reasonable equivalent:   http://extras.humdrum.org/man/humplay

This should have been installed with humdrum-tools.  Try running the command:

```bash
humplay h://chorales/chor001.krn
```

to see if it was compiled.  If not, then you could post the makefile output from compiling:

```
make > report.txt
```

And then copy the contents of report.txt to this thread.  Humplay should compile for MacOS, but might need updating for MIDI in Windows or Linux.

**Comment by craigsapp** [comment]
Also, the [Verovio Humdrum Viewer](https://verovio.humdrum.org) is an online Humdrum editor which also has MIDI playback (but only with piano timbre).

**Comment by lumingpuchheim** [comment]
The compiling is fine. I didn’t know perform no longer exists

**Comment by craigsapp** [comment]
> I didn’t know perform no longer exists

It is not mentioned in the documentation, but should be noted at some point :-).   I have never actually seen the perform command (which is why I created the humplay program).
