### ISSUE TITLE
ydelta no option "o" instead runs as default

### ISSUE THREAD

**Issue by musicnerd** [humdrum-tools/humdrum-tools#5]
I'm getting odd behavior with the "ydelta" command. If I run the -h option it tells me that there is a -o option that allows printing of the lowest value in square brackets ("origin"). When I run ydelta, that actually is the default behavior, and I can't turn it off. When I try to explicitly pass the -o option it gives me an "illegal" error.

**Comment by craigsapp** [comment]
Technically this issue should be reported to https://github.com/humdrum-tools/humdrum/issues in the Humdrum Toolkit repository.   the "humdrum-tools" repository is a meta-repository that allows download of both the Humdrum Toolkit and Humdrum Extras as a single unit.

**Comment by musicnerd** [comment]
moved to /humdrum/issues
